// frontend/src/lib/components/admin/Table/DataTable.svelte
<script lang="ts">
    import { createEventDispatcher } from 'svelte';

    export let columns: { key: string; label: string; sortable?: boolean }[] = [];
    export let data: any[] = [];
    export let loading = false;
    export let totalElements = 0;
    export let pageSize = 10;
    export let currentPage = 0;
    export let actions = true;

    const dispatch = createEventDispatcher();

    function handlePageChange(newPage: number) {
        if (newPage >= 0 && newPage < Math.ceil(totalElements / pageSize)) {
            dispatch('pageChange', newPage);
        }
    }
</script>

<div class="table-container card">
    <table>
        <thead>
            <tr>
                {#each columns as column}
                    <th>{column.label}</th>
                {/each}
                {#if actions}
                    <th class="actions-header">Actions</th>
                {/if}
            </tr>
        </thead>
        <tbody>
            {#if loading}
                <tr>
                    <td colspan={columns.length + (actions ? 1 : 0)} class="loading">
                        <div class="loading-spinner"></div>
                        <span>Loading...</span>
                    </td>
                </tr>
            {:else if data.length === 0}
                <tr>
                    <td colspan={columns.length + (actions ? 1 : 0)} class="empty">No data found</td>
                </tr>
            {:else}
                {#each data as item}
                    <tr>
                        {#each columns as column}
                            <td>{item[column.key]}</td>
                        {/each}
                        {#if actions}
                            <td class="actions">
                                <slot name="actions" {item}>
                                    <button class="icon-btn edit" on:click={() => dispatch('edit', item)} title="Edit">
                                        ✏️
                                    </button>
                                    <button class="icon-btn delete" on:click={() => dispatch('delete', item)} title="Delete">
                                        🗑️
                                    </button>
                                </slot>
                            </td>
                        {/if}
                    </tr>
                {/each}
            {/if}
        </tbody>
    </table>

    <div class="pagination">
        <button class="page-btn" disabled={currentPage === 0} on:click={() => handlePageChange(currentPage - 1)}>
            &larr; Previous
        </button>
        <span class="page-info">Page {currentPage + 1} of {Math.max(1, Math.ceil(totalElements / pageSize))}</span>
        <button
            class="page-btn"
            disabled={currentPage >= Math.ceil(totalElements / pageSize) - 1}
            on:click={() => handlePageChange(currentPage + 1)}
        >
            Next &rarr;
        </button>
    </div>
</div>

<style>
    .table-container {
        width: 100%;
        overflow-x: auto;
        background: var(--color-surface);
        border-radius: var(--radius-md);
        box-shadow: var(--shadow-2);
        border: 1px solid var(--color-outline);
    }

    .card {
        padding: var(--space-md);
    }

    table {
        width: 100%;
        border-collapse: collapse;
        color: var(--color-on-surface);
    }

    th,
    td {
        padding: var(--space-md);
        text-align: left;
        border-bottom: 1px solid var(--color-outline);
    }

    th {
        font-weight: 700;
        color: var(--color-primary);
        font-size: 0.85rem;
        text-transform: uppercase;
        letter-spacing: 1px;
        background: rgba(74, 222, 128, 0.05);
    }

    .actions-header {
        text-align: right;
    }

    .actions {
        display: flex;
        gap: var(--space-sm);
        justify-content: flex-end;
    }

    .loading,
    .empty {
        text-align: center;
        padding: var(--space-xxl);
        color: var(--color-on-surface-variant);
    }

    .loading-spinner {
        width: 2rem;
        height: 2rem;
        border: 3px solid var(--color-surface-variant);
        border-top-color: var(--color-primary);
        border-radius: 50%;
        animation: spin 1s linear infinite;
        margin: 0 auto var(--space-md);
    }

    @keyframes spin {
        to { transform: rotate(360deg); }
    }

    .pagination {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-top: var(--space-md);
        padding-top: var(--space-md);
        border-top: 1px solid var(--color-outline);
    }

    .page-btn {
        padding: var(--space-sm) var(--space-md);
        background: var(--color-surface-variant);
        color: var(--color-on-surface-variant);
        border-radius: var(--radius-sm);
        font-size: 0.85rem;
        font-weight: 600;
    }

    .page-btn:hover:not(:disabled) {
        background: var(--color-primary-container);
        color: var(--color-on-primary-container);
    }

    .page-info {
        font-size: 0.85rem;
        color: var(--color-on-surface-variant);
        font-weight: 500;
    }

    .icon-btn {
        background: var(--color-surface-variant);
        width: 2.5rem;
        height: 2.5rem;
        display: flex;
        align-items: center;
        justify-content: center;
        border-radius: var(--radius-sm);
        font-size: 1rem;
    }

    .icon-btn:hover {
        filter: brightness(1.2);
    }

    .icon-btn.edit:hover { background: var(--color-primary-container); }
    .icon-btn.delete:hover { background: var(--color-error-container); }
</style>

// frontend-react/src/components/admin/DataTable.tsx
"use client";

interface Column {
  key: string;
  label: string;
}

interface DataTableProps<T extends { id: string }> {
  columns: Column[];
  data: T[];
  loading?: boolean;
  totalElements?: number;
  pageSize?: number;
  currentPage?: number;
  /** Render custom action buttons per row. Receives the row item. */
  renderActions?: (item: T) => React.ReactNode;
  onPageChange?: (page: number) => void;
}

export default function DataTable<T extends { id: string }>({
  columns,
  data,
  loading = false,
  totalElements = 0,
  pageSize = 10,
  currentPage = 0,
  renderActions,
  onPageChange,
}: DataTableProps<T>) {
  const totalPages = Math.max(1, Math.ceil(totalElements / pageSize));
  const showActions = !!renderActions;

  function handlePage(next: number) {
    if (next >= 0 && next < totalPages && onPageChange) {
      onPageChange(next);
    }
  }

  return (
    <div className="w-full overflow-x-auto bg-[var(--color-surface)] rounded-[var(--radius-md)] shadow-[var(--shadow-2)] border border-[var(--color-outline)] p-4">
      <table className="w-full border-collapse text-[var(--color-on-surface)]">
        <thead>
          <tr>
            {columns.map((col) => (
              <th
                key={col.key}
                className="p-4 text-left font-bold text-[var(--color-primary)] text-[0.85rem] uppercase tracking-[1px] bg-[rgba(74,222,128,0.05)] border-b border-[var(--color-outline)]"
              >
                {col.label}
              </th>
            ))}
            {showActions && (
              <th className="p-4 text-right font-bold text-[var(--color-primary)] text-[0.85rem] uppercase tracking-[1px] bg-[rgba(74,222,128,0.05)] border-b border-[var(--color-outline)]">
                Actions
              </th>
            )}
          </tr>
        </thead>
        <tbody>
          {loading ? (
            <tr>
              <td
                colSpan={columns.length + (showActions ? 1 : 0)}
                className="p-12 text-center text-[var(--color-on-surface-variant)]"
              >
                <div className="w-8 h-8 border-[3px] border-[var(--color-surface-variant)] border-t-[var(--color-primary)] rounded-full animate-spin-slow mx-auto mb-4" />
                <span>Loading…</span>
              </td>
            </tr>
          ) : data.length === 0 ? (
            <tr>
              <td
                colSpan={columns.length + (showActions ? 1 : 0)}
                className="p-12 text-center text-[var(--color-on-surface-variant)]"
              >
                No data found
              </td>
            </tr>
          ) : (
            data.map((item) => (
              <tr
                key={item.id}
                className="border-b border-[var(--color-outline)] hover:bg-[var(--color-surface-variant)]/20 transition-colors"
              >
                {columns.map((col) => (
                  <td key={col.key} className="p-4">
                    {String((item as Record<string, unknown>)[col.key] ?? "")}
                  </td>
                ))}
                {showActions && (
                  <td className="p-4">
                    <div className="flex gap-2 justify-end">
                      {renderActions(item)}
                    </div>
                  </td>
                )}
              </tr>
            ))
          )}
        </tbody>
      </table>

      {/* Pagination */}
      <div className="flex justify-between items-center mt-4 pt-4 border-t border-[var(--color-outline)]">
        <button
          disabled={currentPage === 0}
          onClick={() => handlePage(currentPage - 1)}
          className="px-4 py-2 bg-[var(--color-surface-variant)] text-[var(--color-on-surface-variant)] rounded-[var(--radius-sm)] text-[0.85rem] font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-[var(--color-primary-container)] hover:text-[var(--color-on-primary-container)] transition-colors"
        >
          ← Previous
        </button>
        <span className="text-[0.85rem] text-[var(--color-on-surface-variant)] font-medium">
          Page {currentPage + 1} of {totalPages}
        </span>
        <button
          disabled={currentPage >= totalPages - 1}
          onClick={() => handlePage(currentPage + 1)}
          className="px-4 py-2 bg-[var(--color-surface-variant)] text-[var(--color-on-surface-variant)] rounded-[var(--radius-sm)] text-[0.85rem] font-semibold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-[var(--color-primary-container)] hover:text-[var(--color-on-primary-container)] transition-colors"
        >
          Next →
        </button>
      </div>
    </div>
  );
}
