// frontend/src/lib/components/admin/Navigation/Sidebar.svelte
<script lang="ts">
    import { page } from '$app/stores';

    export let open = true;

    const links = [
        { href: '/admin/categories', label: 'Categories', icon: '📁' },
        { href: '/admin/questions', label: 'Questions', icon: '❓' },
    ];

    $: currentPath = $page.url.pathname;
</script>

<aside class:open>
    <div class="logo">
        <h2>Football 501</h2>
        <span class="badge">Admin</span>
    </div>

    <nav>
        <ul>
            {#each links as link}
                <li>
                    <a
                        href={link.href}
                        class:active={currentPath.startsWith(link.href)}
                    >
                        <span class="icon">{link.icon}</span>
                        <span class="label">{link.label}</span>
                    </a>
                </li>
            {/each}
        </ul>
    </nav>

    <div class="footer">
        <a href="/" class="back-link">
            <span class="icon">⬅️</span>
            <span class="label">Back to Game</span>
        </a>
    </div>
</aside>

<style>
    aside {
        width: 250px;
        height: 100vh;
        background: var(--color-surface);
        border-right: 1px solid var(--color-outline);
        display: flex;
        flex-direction: column;
        transition: transform 0.3s ease;
        position: fixed;
        left: 0;
        top: 0;
        z-index: 100;
        box-shadow: var(--shadow-2);
    }

    .logo {
        padding: var(--space-lg);
        border-bottom: 1px solid var(--color-outline);
        display: flex;
        align-items: center;
        gap: var(--space-sm);
    }

    h2 {
        margin: 0;
        font-size: 1.25rem;
        color: var(--color-primary);
        font-weight: 800;
    }

    .badge {
        background: var(--color-primary-container);
        padding: 0.2rem 0.5rem;
        border-radius: var(--radius-xs);
        font-size: 0.65rem;
        color: var(--color-on-primary-container);
        text-transform: uppercase;
        font-weight: 800;
        letter-spacing: 0.5px;
    }

    nav {
        flex: 1;
        padding: var(--space-md);
    }

    ul {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    li {
        margin-bottom: var(--space-xs);
    }

    a {
        display: flex;
        align-items: center;
        gap: var(--space-md);
        padding: var(--space-md);
        color: var(--color-on-surface-variant);
        text-decoration: none;
        border-radius: var(--radius-sm);
        transition: all 0.2s;
        font-weight: 500;
    }

    a:hover {
        background: var(--color-surface-variant);
        color: var(--color-on-surface);
    }

    a.active {
        background: var(--color-primary-container);
        color: var(--color-on-primary-container);
    }

    .icon {
        font-size: 1.25rem;
    }

    .footer {
        padding: var(--space-md);
        border-top: 1px solid var(--color-outline);
    }

    .back-link {
        color: var(--color-error);
        font-weight: 600;
    }

    .back-link:hover {
        background: var(--color-error-container);
        color: var(--color-on-error-container);
    }
</style>

// frontend-react/src/components/admin/Sidebar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";

const links = [
  { href: "/admin/categories", label: "Categories", icon: "📁" },
  { href: "/admin/questions", label: "Questions", icon: "❓" },
];

export default function Sidebar() {
  const pathname = usePathname();

  return (
    <aside
      className="w-[250px] h-screen bg-[var(--color-surface)] border-r border-[var(--color-outline)] flex flex-col fixed left-0 top-0 z-[100] shadow-[var(--shadow-2)]"
    >
      {/* Logo */}
      <div className="px-6 py-5 border-b border-[var(--color-outline)] flex items-center gap-2">
        <h2 className="m-0 text-xl text-[var(--color-primary)] font-extrabold">
          Football 501
        </h2>
        <span className="bg-[var(--color-primary-container)] text-[var(--color-on-primary-container)] text-[0.65rem] uppercase font-extrabold tracking-[0.5px] px-2 py-[0.2rem] rounded-[var(--radius-xs)]">
          Admin
        </span>
      </div>

      {/* Nav */}
      <nav className="flex-1 p-4">
        <ul className="list-none p-0 m-0">
          {links.map((link) => {
            const isActive = pathname.startsWith(link.href);
            return (
              <li key={link.href} className="mb-1">
                <Link
                  href={link.href}
                  className={[
                    "flex items-center gap-4 px-4 py-4 rounded-[var(--radius-sm)] font-medium no-underline transition-all duration-200",
                    isActive
                      ? "bg-[var(--color-primary-container)] text-[var(--color-on-primary-container)]"
                      : "text-[var(--color-on-surface-variant)] hover:bg-[var(--color-surface-variant)] hover:text-[var(--color-on-surface)]",
                  ].join(" ")}
                >
                  <span className="text-xl">{link.icon}</span>
                  <span>{link.label}</span>
                </Link>
              </li>
            );
          })}
        </ul>
      </nav>

      {/* Footer */}
      <div className="p-4 border-t border-[var(--color-outline)]">
        <Link
          href="/"
          className="flex items-center gap-4 px-4 py-4 rounded-[var(--radius-sm)] font-semibold no-underline text-[var(--color-error)] hover:bg-[var(--color-error-container)] hover:text-[var(--color-on-error-container)] transition-all duration-200"
        >
          <span className="text-xl">⬅️</span>
          <span>Back to Game</span>
        </Link>
      </div>
    </aside>
  );
}
