// frontend/src/lib/components/PlayerSearch.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import { getFlagEmoji } from '$lib/utils/country';

	export let value = '';
	export let disabled = false;
	export let placeholder = 'Enter player name...';

	const dispatch = createEventDispatcher();
	let suggestions: Array<{ id: string; name: string; nationality: string }> = [];
	let showSuggestions = false;
	let loading = false;
	let debounceTimer: NodeJS.Timeout;
	let inputElement: HTMLInputElement;

	// API Base URL - strictly for search
	// Note: We should ideally pass this as a prop or env var, but keeping consistent with +page.svelte
	const API_BASE = 'http://localhost:8080/api';

	function handleInput(event: Event) {
		const target = event.target as HTMLInputElement;
		value = target.value;
		
		clearTimeout(debounceTimer);
		
		if (value.length < 2) {
			suggestions = [];
			showSuggestions = false;
			return;
		}

		debounceTimer = setTimeout(() => {
			fetchSuggestions(value);
		}, 300);
	}

	async function fetchSuggestions(query: string) {
		loading = true;
		try {
			const response = await fetch(`${API_BASE}/players/search?query=${encodeURIComponent(query)}`);
			if (response.ok) {
				suggestions = await response.json();
				showSuggestions = suggestions.length > 0;
			}
		} catch (error) {
			console.error('Error fetching suggestions:', error);
		} finally {
			loading = false;
		}
	}

	function selectPlayer(player: { name: string }) {
		value = player.name;
		suggestions = [];
		showSuggestions = false;
		inputElement.focus();
	}

	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Enter') {
			event.preventDefault(); // Prevent form submission if inside one
			dispatch('submit');
			showSuggestions = false;
		}
		// TODO: Add arrow key navigation
	}

	function handleBlur() {
		// Delay hiding to allow click event on suggestion to fire
		setTimeout(() => {
			showSuggestions = false;
		}, 200);
	}
</script>

<div class="player-search">
	<div class="input-wrapper">
		<input
			type="text"
			bind:this={inputElement}
			{value}
			{disabled}
			{placeholder}
			on:input={handleInput}
			on:keydown={handleKeydown}
			on:blur={handleBlur}
			autocomplete="off"
		/>
		{#if loading}
			<div class="spinner"></div>
		{/if}
	</div>

	{#if showSuggestions}
		<ul class="suggestions">
			{#each suggestions as player}
				<li>
					<button on:click={() => selectPlayer(player)} class="suggestion-btn">
						<span class="name">{player.name}</span>
						{#if player.nationality}
							<span class="nationality" title={player.nationality}>{getFlagEmoji(player.nationality)}</span>
						{/if}
					</button>
				</li>
			{/each}
		</ul>
	{/if}
</div>

<style>
	.player-search {
		position: relative;
		width: 100%;
	}

	.input-wrapper {
		position: relative;
		display: flex;
		align-items: center;
	}

	input {
		width: 100%;
		padding: 0.75rem 1rem;
		font-size: 1rem;
		border: 2px solid #4ade80;
		border-radius: 8px;
		background: #1a1a1a;
		color: #fff;
		box-sizing: border-box;
	}

	input:focus {
		outline: none;
		border-color: #22c55e;
		box-shadow: 0 0 0 3px rgba(74, 222, 128, 0.1);
	}

	input:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.spinner {
		position: absolute;
		right: 1rem;
		width: 1rem;
		height: 1rem;
		border: 2px solid #4ade80;
		border-top-color: transparent;
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		to { transform: rotate(360deg); }
	}

	.suggestions {
		position: absolute;
		top: 100%;
		left: 0;
		right: 0;
		margin: 0.5rem 0 0;
		padding: 0;
		list-style: none;
		background: #2a2a2a;
		border: 1px solid #4ade80;
		border-radius: 8px;
		max-height: 200px;
		overflow-y: auto;
		z-index: 10;
		box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
	}

	.suggestion-btn {
		width: 100%;
		text-align: left;
		padding: 0.75rem 1rem;
		background: none;
		border: none;
		color: #fff;
		cursor: pointer;
		display: flex;
		justify-content: space-between;
		align-items: center;
		transition: background 0.2s;
	}

	.suggestion-btn:hover {
		background: #374151;
	}

	.name {
		font-weight: 500;
	}

	.nationality {
		color: #9ca3af;
		font-size: 0.875rem;
	}
</style>

// frontend-react/src/components/game/PlayerSearch.tsx
"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { getFlagEmoji } from "@/utils/country";

interface Suggestion {
  id: string;
  name: string;
  nationality: string;
}

interface PlayerSearchProps {
  value: string;
  onChange: (value: string) => void;
  onSubmit: () => void;
  disabled?: boolean;
  placeholder?: string;
}

export default function PlayerSearch({
  value,
  onChange,
  onSubmit,
  disabled = false,
  placeholder = "Enter player name...",
}: PlayerSearchProps) {
  const [suggestions, setSuggestions] = useState<Suggestion[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [loading, setLoading] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const fetchSuggestions = useCallback(async (query: string) => {
    setLoading(true);
    try {
      const res = await fetch(
        `/api/players/search?query=${encodeURIComponent(query)}`
      );
      if (res.ok) {
        const data: Suggestion[] = await res.json();
        setSuggestions(data);
        setShowSuggestions(data.length > 0);
      }
    } catch (err) {
      console.error("Error fetching player suggestions:", err);
    } finally {
      setLoading(false);
    }
  }, []);

  function handleChange(e: React.ChangeEvent<HTMLInputElement>) {
    const val = e.target.value;
    onChange(val);

    // Clear pending debounce
    if (debounceRef.current) clearTimeout(debounceRef.current);

    if (val.length < 2) {
      setSuggestions([]);
      setShowSuggestions(false);
      return;
    }

    debounceRef.current = setTimeout(() => {
      fetchSuggestions(val);
    }, 300);
  }

  // Cancel pending debounce on unmount
  useEffect(() => {
    return () => {
      if (debounceRef.current) clearTimeout(debounceRef.current);
    };
  }, []);

  function selectPlayer(player: Suggestion) {
    onChange(player.name);
    setSuggestions([]);
    setShowSuggestions(false);
    inputRef.current?.focus();
  }

  function handleKeyDown(e: React.KeyboardEvent<HTMLInputElement>) {
    if (e.key === "Enter") {
      e.preventDefault();
      setShowSuggestions(false);
      onSubmit();
    }
  }

  function handleBlur() {
    // Delay so click on a suggestion fires before hiding
    setTimeout(() => setShowSuggestions(false), 200);
  }

  return (
    <div className="relative w-full">
      {/* Input row */}
      <div className="relative flex items-center">
        <input
          ref={inputRef}
          type="text"
          value={value}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
          onBlur={handleBlur}
          disabled={disabled}
          placeholder={placeholder}
          autoComplete="off"
          className="w-full box-border px-4 py-3 text-base border-2 border-[var(--color-primary)] rounded-lg bg-[#1a1a1a] text-white focus:outline-none focus:border-[#22c55e] focus:shadow-[0_0_0_3px_rgba(74,222,128,0.1)] disabled:opacity-50 disabled:cursor-not-allowed transition-all"
        />
        {loading && (
          <div className="absolute right-4 w-4 h-4 border-2 border-[var(--color-primary)] border-t-transparent rounded-full animate-spin-slow" />
        )}
      </div>

      {/* Suggestions dropdown */}
      {showSuggestions && (
        <ul className="absolute top-full left-0 right-0 mt-2 p-0 m-0 list-none bg-[#2a2a2a] border border-[var(--color-primary)] rounded-lg max-h-[200px] overflow-y-auto z-10 shadow-[0_4px_6px_rgba(0,0,0,0.3)] animate-slide-down">
          {suggestions.map((player) => (
            <li key={player.id}>
              <button
                onMouseDown={() => selectPlayer(player)} // mousedown fires before blur
                className="w-full text-left px-4 py-3 bg-transparent border-none text-white cursor-pointer flex justify-between items-center hover:bg-[#374151] transition-colors"
              >
                <span className="font-medium">{player.name}</span>
                {player.nationality && (
                  <span className="text-[#9ca3af] text-sm" title={player.nationality}>
                    {getFlagEmoji(player.nationality)}
                  </span>
                )}
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
