// frontend-react/src/components/ui/Select.tsx
interface SelectOption {
  value: string | boolean | number;
  label: string;
}

interface SelectProps {
  label: string;
  value: string | boolean | number;
  onChange: (value: string) => void;
  options: SelectOption[];
  required?: boolean;
  disabled?: boolean;
  error?: string;
}

export default function Select({
  label,
  value,
  onChange,
  options,
  required = false,
  disabled = false,
  error = "",
}: SelectProps) {
  return (
    <div className="flex flex-col gap-1 mb-4">
      <label className="text-[var(--color-on-surface-variant)] text-[0.85rem] font-semibold tracking-[0.5px]">
        {label}
        {required && (
          <span className="text-[var(--color-error)] ml-1">*</span>
        )}
      </label>
      <div className="flex flex-col gap-1">
        <select
          value={String(value)}
          onChange={(e) => onChange(e.target.value)}
          disabled={disabled}
          className={[
            "w-full box-border p-4 text-base cursor-pointer transition-all duration-200",
            "bg-[var(--color-surface)] text-[var(--color-on-surface)]",
            "border rounded-[var(--radius-sm)]",
            "focus:outline-none focus:border-2 focus:border-[var(--color-primary)] focus:shadow-[0_0_0_4px_rgba(74,222,128,0.1)]",
            "disabled:opacity-50 disabled:bg-[#252525]",
            error
              ? "border-[var(--color-error)]"
              : "border-[var(--color-outline)]",
          ].join(" ")}
        >
          {options.map((opt) => (
            <option key={String(opt.value)} value={String(opt.value)}>
              {opt.label}
            </option>
          ))}
        </select>
        {error && (
          <span className="text-[var(--color-error)] text-xs font-medium">
            {error}
          </span>
        )}
      </div>
    </div>
  );
}

// frontend/src/lib/components/admin/Form/Select.svelte
<script lang="ts">
    export let label: string;
    export let value: string | boolean;
    export let options: { value: string | boolean; label: string }[] = [];
    export let required = false;
    export let disabled = false;
    export let error = '';
</script>

<div class="form-group">
    <label>
        {label}
        {#if required}<span class="required">*</span>{/if}
    </label>
    <div class="input-container">
        <select bind:value {disabled} class:has-error={!!error}>
            {#each options as option}
                <option value={option.value}>{option.label}</option>
            {/each}
        </select>
        {#if error}
            <span class="error-text">{error}</span>
        {/if}
    </div>
</div>

<style>
    .form-group {
        display: flex;
        flex-direction: column;
        gap: var(--space-xs);
        margin-bottom: var(--space-md);
    }

    label {
        color: var(--color-on-surface-variant);
        font-size: 0.85rem;
        font-weight: 600;
        letter-spacing: 0.5px;
    }

    .required {
        color: var(--color-error);
        margin-left: 0.2rem;
    }

    .input-container {
        display: flex;
        flex-direction: column;
        gap: var(--space-xs);
    }

    select {
        width: 100%;
        box-sizing: border-box;
        padding: var(--space-md);
        background: var(--color-surface);
        border: 1px solid var(--color-outline);
        border-radius: var(--radius-sm);
        color: var(--color-on-surface);
        font-size: 1rem;
        cursor: pointer;
        transition: all 0.2s;
    }

    select:focus {
        outline: none;
        border-color: var(--color-primary);
        border-width: 2px;
        padding: calc(var(--space-md) - 1px);
        box-shadow: 0 0 0 4px rgba(74, 222, 128, 0.1);
    }

    select.has-error {
        border-color: var(--color-error);
    }

    .error-text {
        color: var(--color-error);
        font-size: 0.75rem;
        font-weight: 500;
    }

    select:disabled {
        opacity: 0.5;
        background: #252525;
    }
</style>
