// frontend/src/lib/components/admin/Category/CategoryForm.svelte
<script lang="ts">
    import TextField from '$lib/components/admin/Form/TextField.svelte';
    import TextArea from '$lib/components/admin/Form/TextArea.svelte';
    import type { Category, CreateCategoryRequest } from '$lib/types/admin';

    export let category: Category | undefined = undefined;
    export let loading = false;

    let name = category?.name || '';
    let slug = category?.slug || '';
    let description = category?.description || '';
    let errors: Record<string, string> = {};

    $: isEdit = !!category;

    function validate() {
        errors = {};
        if (!name.trim()) errors.name = 'Name is required';
        if (!isEdit && !slug.trim()) errors.slug = 'Slug is required';
        if (!isEdit && slug && !/^[a-z0-9-]+$/.test(slug)) {
            errors.slug = 'Slug must contain only lowercase letters, numbers, and hyphens';
        }
        return Object.keys(errors).length === 0;
    }

    // Auto-generate slug from name if creating
    function handleNameInput() {
        if (!isEdit && !category && name) {
            slug = name.toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-|-$/g, '');
        }
    }

    import { createEventDispatcher } from 'svelte';
    const dispatch = createEventDispatcher();

    function handleSubmit() {
        if (!validate()) return;

        const data = {
            name,
            description,
            ...(isEdit ? {} : { slug })
        };

        dispatch('submit', data);
    }
</script>

<form on:submit|preventDefault={handleSubmit}>
    <TextField
        label="Name"
        bind:value={name}
        required
        error={errors.name}
        on:input={handleNameInput}
        disabled={loading}
    />

    <TextField
        label="Slug"
        bind:value={slug}
        required={!isEdit}
        disabled={isEdit || loading}
        error={errors.slug}
        placeholder="e.g. premier-league"
    />

    <TextArea
        label="Description"
        bind:value={description}
        disabled={loading}
        rows={3}
    />

    <div class="actions">
        <button type="button" class="cancel-btn" on:click={() => dispatch('cancel')} disabled={loading}>
            Cancel
        </button>
        <button type="submit" class="submit-btn" disabled={loading}>
            {loading ? 'Saving...' : (isEdit ? 'Update Category' : 'Create Category')}
        </button>
    </div>
</form>

<style>
    .actions {
        display: flex;
        justify-content: flex-end;
        gap: 1rem;
        margin-top: 2rem;
        padding-top: 1rem;
        border-top: 1px solid #444;
    }

    button {
        padding: 0.75rem 1.5rem;
        border-radius: 6px;
        border: none;
        cursor: pointer;
        font-weight: 500;
        font-size: 1rem;
    }

    .cancel-btn {
        background: #444;
        color: #fff;
    }

    .submit-btn {
        background: #4ade80;
        color: #000;
    }

    button:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    button:hover:not(:disabled) {
        opacity: 0.9;
    }
</style>

// frontend-react/src/components/admin/forms/CategoryForm.tsx
"use client";

import { useEffect, useState } from "react";
import TextField from "@/components/ui/TextField";
import TextArea from "@/components/ui/TextArea";
import type { Category, CreateCategoryRequest, UpdateCategoryRequest } from "@/lib/types/admin";

interface CategoryFormProps {
  category?: Category;
  loading?: boolean;
  onSubmit: (data: CreateCategoryRequest | UpdateCategoryRequest) => void;
  onCancel: () => void;
}

export default function CategoryForm({
  category,
  loading = false,
  onSubmit,
  onCancel,
}: CategoryFormProps) {
  const isEdit = !!category;

  const [name, setName] = useState(category?.name ?? "");
  const [slug, setSlug] = useState(category?.slug ?? "");
  const [description, setDescription] = useState(category?.description ?? "");
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Auto-generate slug from name when creating
  function handleNameChange(val: string) {
    setName(val);
    if (!isEdit) {
      setSlug(
        val
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/^-|-$/g, "")
      );
    }
  }

  function validate(): boolean {
    const errs: Record<string, string> = {};
    if (!name.trim()) errs.name = "Name is required";
    if (!isEdit && !slug.trim()) errs.slug = "Slug is required";
    if (!isEdit && slug && !/^[a-z0-9-]+$/.test(slug)) {
      errs.slug = "Slug must contain only lowercase letters, numbers, and hyphens";
    }
    setErrors(errs);
    return Object.keys(errs).length === 0;
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;

    if (isEdit) {
      onSubmit({ name, description } as UpdateCategoryRequest);
    } else {
      onSubmit({ name, slug, description } as CreateCategoryRequest);
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      <TextField
        label="Name"
        value={name}
        onChange={handleNameChange}
        required
        error={errors.name}
        disabled={loading}
      />

      <TextField
        label="Slug"
        value={slug}
        onChange={setSlug}
        required={!isEdit}
        disabled={isEdit || loading}
        error={errors.slug}
        placeholder="e.g. premier-league"
      />

      <TextArea
        label="Description"
        value={description}
        onChange={setDescription}
        disabled={loading}
        rows={3}
      />

      <div className="flex justify-end gap-4 mt-8 pt-4 border-t border-white/10">
        <button
          type="button"
          onClick={onCancel}
          disabled={loading}
          className="px-6 py-3 rounded-lg bg-[#444] text-white font-medium text-base disabled:opacity-50 disabled:cursor-not-allowed hover:opacity-90 transition-opacity"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={loading}
          className="px-6 py-3 rounded-lg bg-[var(--color-primary)] text-black font-medium text-base disabled:opacity-50 disabled:cursor-not-allowed hover:opacity-90 transition-opacity"
        >
          {loading ? "Saving…" : isEdit ? "Update Category" : "Create Category"}
        </button>
      </div>
    </form>
  );
}
