// frontend/src/lib/components/admin/Question/QuestionForm.svelte
<script lang="ts">
    import TextField from '$lib/components/admin/Form/TextField.svelte';
    import TextArea from '$lib/components/admin/Form/TextArea.svelte';
    import Select from '$lib/components/admin/Form/Select.svelte';
    import type { Question, Category } from '$lib/types/admin';
    import { createEventDispatcher } from 'svelte';

    export let question: Question | undefined = undefined;
    export let categories: Category[] = [];
    export let loading = false;

    let categoryId = question?.categoryId || '';
    let questionText = question?.questionText || '';
    let metricKey = question?.metricKey || '';
    let minScore = question?.minScore?.toString() || '';
    let difficulty = question?.difficulty?.toString() || '2';
    let configJson = question?.config ? JSON.stringify(question.config, null, 2) : '{}';
    
    let errors: Record<string, string> = {};

    const dispatch = createEventDispatcher();

    function validate() {
        errors = {};
        if (!categoryId) errors.categoryId = 'Category is required';
        if (!questionText.trim()) errors.questionText = 'Question text is required';
        if (!metricKey.trim()) errors.metricKey = 'Metric key is required';
        
        try {
            JSON.parse(configJson);
        } catch (e) {
            errors.config = 'Invalid JSON format';
        }

        if (minScore && isNaN(Number(minScore))) {
            errors.minScore = 'Must be a number';
        }

        return Object.keys(errors).length === 0;
    }

    function handleSubmit() {
        if (!validate()) return;

        const data = {
            categoryId,
            questionText,
            metricKey,
            minScore: minScore ? Number(minScore) : undefined,
            difficulty: Number(difficulty),
            config: JSON.parse(configJson)
        };

        dispatch('submit', data);
    }

    // Transform categories for Select component
    $: categoryOptions = [
        { value: '', label: 'Select a Category' },
        ...categories.map(c => ({ value: c.id, label: c.name }))
    ];

    const difficultyOptions = [
        { value: '1', label: 'Easy' },
        { value: '2', label: 'Medium' },
        { value: '3', label: 'Hard' }
    ];
</script>

<form on:submit|preventDefault={handleSubmit}>
    <Select
        label="Category"
        bind:value={categoryId}
        options={categoryOptions}
        required
        error={errors.categoryId}
        disabled={loading}
    />

    <Select
        label="Difficulty"
        bind:value={difficulty}
        options={difficultyOptions}
        required
        disabled={loading}
    />

    <TextArea
        label="Question Text"
        bind:value={questionText}
        required
        rows={2}
        error={errors.questionText}
        disabled={loading}
        placeholder="e.g. Which player has the most Premier League appearances?"
    />

    <TextField
        label="Metric Key"
        bind:value={metricKey}
        required
        error={errors.metricKey}
        disabled={loading}
        placeholder="e.g. appearances"
    />

    <TextField
        label="Minimum Score (Optional)"
        bind:value={minScore}
        type="number"
        error={errors.minScore}
        disabled={loading}
        placeholder="0"
    />

    <TextArea
        label="Configuration (JSON)"
        bind:value={configJson}
        rows={5}
        error={errors.config}
        disabled={loading}
        placeholder="JSON object"
    />

    <div class="actions">
        <button type="button" class="cancel-btn" on:click={() => dispatch('cancel')} disabled={loading}>
            Cancel
        </button>
        <button type="submit" class="submit-btn" disabled={loading}>
            {loading ? 'Saving...' : (question ? 'Update Question' : 'Create Question')}
        </button>
    </div>
</form>

<style>
    .actions {
        display: flex;
        justify-content: flex-end;
        gap: 1rem;
        margin-top: 2rem;
        padding-top: 1rem;
        border-top: 1px solid #444;
    }

    button {
        padding: 0.75rem 1.5rem;
        border-radius: 6px;
        border: none;
        cursor: pointer;
        font-weight: 500;
        font-size: 1rem;
    }

    .cancel-btn {
        background: #444;
        color: #fff;
    }

    .submit-btn {
        background: #4ade80;
        color: #000;
    }

    button:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    button:hover:not(:disabled) {
        opacity: 0.9;
    }
</style>

// frontend-react/src/components/admin/forms/QuestionForm.tsx
"use client";

import { useState } from "react";
import TextField from "@/components/ui/TextField";
import TextArea from "@/components/ui/TextArea";
import Select from "@/components/ui/Select";
import type {
  Question,
  Category,
  CreateQuestionRequest,
  UpdateQuestionRequest,
} from "@/lib/types/admin";

interface QuestionFormProps {
  question?: Question;
  categories: Category[];
  loading?: boolean;
  onSubmit: (data: CreateQuestionRequest | UpdateQuestionRequest) => void;
  onCancel: () => void;
}

const difficultyOptions = [
  { value: "1", label: "Easy" },
  { value: "2", label: "Medium" },
  { value: "3", label: "Hard" },
];

export default function QuestionForm({
  question,
  categories,
  loading = false,
  onSubmit,
  onCancel,
}: QuestionFormProps) {
  const isEdit = !!question;

  const [categoryId, setCategoryId] = useState(question?.categoryId ?? "");
  const [questionText, setQuestionText] = useState(question?.questionText ?? "");
  const [metricKey, setMetricKey] = useState(question?.metricKey ?? "");
  const [minScore, setMinScore] = useState(question?.minScore?.toString() ?? "");
  const [difficulty, setDifficulty] = useState(
    question?.difficulty?.toString() ?? "2"
  );
  const [configJson, setConfigJson] = useState(
    question?.config ? JSON.stringify(question.config, null, 2) : "{}"
  );
  const [errors, setErrors] = useState<Record<string, string>>({});

  const categoryOptions = [
    { value: "", label: "Select a Category" },
    ...categories.map((c) => ({ value: c.id, label: c.name })),
  ];

  function validate(): boolean {
    const errs: Record<string, string> = {};
    if (!categoryId) errs.categoryId = "Category is required";
    if (!questionText.trim()) errs.questionText = "Question text is required";
    if (!metricKey.trim()) errs.metricKey = "Metric key is required";
    try {
      JSON.parse(configJson);
    } catch {
      errs.config = "Invalid JSON format";
    }
    if (minScore && isNaN(Number(minScore))) errs.minScore = "Must be a number";
    setErrors(errs);
    return Object.keys(errs).length === 0;
  }

  function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!validate()) return;

    onSubmit({
      categoryId,
      questionText,
      metricKey,
      minScore: minScore ? Number(minScore) : undefined,
      difficulty: Number(difficulty),
      config: JSON.parse(configJson),
    });
  }

  return (
    <form onSubmit={handleSubmit}>
      <Select
        label="Category"
        value={categoryId}
        onChange={setCategoryId}
        options={categoryOptions}
        required
        error={errors.categoryId}
        disabled={loading}
      />

      <Select
        label="Difficulty"
        value={difficulty}
        onChange={setDifficulty}
        options={difficultyOptions}
        required
        disabled={loading}
      />

      <TextArea
        label="Question Text"
        value={questionText}
        onChange={setQuestionText}
        required
        rows={2}
        error={errors.questionText}
        disabled={loading}
        placeholder="e.g. Which player has the most Premier League appearances?"
      />

      <TextField
        label="Metric Key"
        value={metricKey}
        onChange={setMetricKey}
        required
        error={errors.metricKey}
        disabled={loading}
        placeholder="e.g. appearances"
      />

      <TextField
        label="Minimum Score (Optional)"
        value={minScore}
        onChange={setMinScore}
        type="number"
        error={errors.minScore}
        disabled={loading}
        placeholder="0"
      />

      <TextArea
        label="Configuration (JSON)"
        value={configJson}
        onChange={setConfigJson}
        rows={5}
        error={errors.config}
        disabled={loading}
        placeholder="JSON object"
      />

      <div className="flex justify-end gap-4 mt-8 pt-4 border-t border-white/10">
        <button
          type="button"
          onClick={onCancel}
          disabled={loading}
          className="px-6 py-3 rounded-lg bg-[#444] text-white font-medium text-base disabled:opacity-50 disabled:cursor-not-allowed hover:opacity-90 transition-opacity"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={loading}
          className="px-6 py-3 rounded-lg bg-[var(--color-primary)] text-black font-medium text-base disabled:opacity-50 disabled:cursor-not-allowed hover:opacity-90 transition-opacity"
        >
          {loading ? "Saving…" : isEdit ? "Update Question" : "Create Question"}
        </button>
      </div>
    </form>
  );
}
